---
title: "Data Processing"
author: "TZiegler"
date: "22 April 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Synopsis

This file loads the data and processes it and store it to the correct output.


### Load all necessury libraries
```{r}
suppressMessages(library(ggplot2))
suppressMessages(library("readxl"))
suppressMessages(library(dplyr))
```

### Load data
```{r}
sample <- read_excel("../data_capex.xlsx", na = "")

sample <- as.data.frame(sample)
str(sample)

## Subsetting the original data
sample2 <- sample[,1:16]
str(sample2)

## Remove obsolete data
sample2 <- subset(sample2, account != 5001)

## Write as csv file
write.csv(sample2, file = "data/data_capex.csv")
```

### Convert relevant numbers to integer
```{r}

```


### Group data by client_propert_id and calclulate costs
```{r}
property_costs <- sample %>% filter(!is.na(year_construction)) %>%
        group_by(sub_pid, client_property_id, year_construction, sqm) %>%
        summarize(costs = sum(costs))

prop_costs <- as.data.frame(property_costs)

prop_costs <- arrange(prop_costs, desc(costs))
prop_costs


```

### Print actions per asset
```{r}
assetid <- "3001"
showdata <- subset(sample, client_property_id == assetid & actions != "WEG-Wohngeld")
showdata <- arrange(showdata, desc(costs))
showdata
```

